#' Run a Python Script for Profile Prediction
#'
#' This function runs a specified Python script using the `reticulate` package.
#'
#' @param script_path Character. The path to the Python script to be executed.
#' @param script_dir Character. The directory where the Python script resides.
#' @param profile_main_dir Character.
#' The main directory containing profile data.
#' @param profile_sub_dir Character.
#' The subdirectory within the main profile directory.
#' @param model_path Character.
#' The path to the trained model file to be used for prediction.
#' @param name_prefix Character.
#' A prefix to be added to the output files generated by the Python script.
#' @param threshold Numeric.
#' The probability threshold for classifying predictions. Default is 0.5.
#' @param file_format Character.
#' The format of the profile files (e.g., "parquet", "csv").
#' Default is "parquet".
#'
#' @return None. This function is used for its side effects of
#' running the Python script.
#'
#' @details
#' The function first checks if the specified Python script exists.
#' If the script exists, it constructs a command string to pass
#' the required arguments and runs the script using `reticulate::py_run_string`.
#' The command includes various parameters like the working directory,
#' profile directories, model path,
#' output name prefix, classification threshold, and file format.
#'
#' If the script does not exist, the function stops and throws an error message.
#'
#' @importFrom reticulate py_run_string
#'
#' @examples
#' \dontrun{
#' run_prediction_python_script(
#'   script_path = "path/to/predict_profile_probabilities.py",
#'   script_dir = "path/to/scripts",
#'   profile_main_dir = "path/to/profiles/main",
#'   profile_sub_dir = "subdir_name",
#'   model_path = "path/to/model.h5",
#'   name_prefix = "output_prefix",
#'   threshold = 0.7,
#'   file_format = "parquet"
#' )
#' }
#'
run_prediction_python_script <- function(script_path,
                                         script_dir,
                                         profile_main_dir,
                                         profile_sub_dir,
                                         model_path, name_prefix,
                                         threshold = 0.5,
                                         file_format = "parquet") {
  # Check if the script exists
  if (file.exists(script_path)) {
    # Create a Python command with the required arguments
    command <- sprintf(
      "import sys; sys.argv = ['%s', '-w', '%s', '-p', '%s', '-r', '%s', '-m', '%s', '-n', '%s', '-t', '%f', '-f', '%s']; exec(open('%s').read())", # nolint: line_length_linter.
      script_path, script_dir, profile_main_dir, profile_sub_dir, model_path, name_prefix, threshold, file_format, script_path # nolint: line_length_linter.
    )
    # Run the Python script with arguments
    reticulate::py_run_string(command)
  } else {
    stop("The specified script does not exist.")
  }
}

#' Process All Prediction Files
#'
#' This function processes all files matching
#' a specified pattern in a given directory.
#' It reads each file, applies the `wrapup_filter_bed_to_reduce` function
#' from the `PRIMEloci` package,
#' and stores the results in a `GRangesList`.
#'
#' @param prediction_dir Character.
#' The directory where the prediction files are located.
#' @param partial_name Character.
#' A pattern to match files in the `prediction_dir`.
#'
#' @return A `GRangesList` object containing the processed results
#' from all matching files.
#'
#' @details
#' The function lists all files in the specified directory
#' that match the given pattern.
#' For each file, it applies the `wrapup_filter_bed_to_reduce` function
#' and stores the result in a `GRangesList` object.
#' If no files are found matching the pattern, the function stops
#' and throws an error.
#'
#' @importFrom GenomicRanges GRangesList
#' @importFrom tools file_path_sans_ext
#'
#' @examples
#' \dontrun{
#' gr_list <- process_all_files(
#'   prediction_dir = "path/to/predictions",
#'   partial_name = "pattern_to_match"
#' )
#' }
#'
process_all_files <- function(prediction_dir, partial_name) {
  # List all files matching the partial name in the specified directory
  files <- list.files(path = prediction_dir,
                      pattern = partial_name,
                      full.names = TRUE)

  if (length(files) == 0) {
    stop("No files found matching the pattern in the specified directory.")
  }

  gr_list <- GenomicRanges::GRangesList()  # Initialize an empty GRangesList

  for (file in files) {
    writeLines(paste("Processing", file, "..."))

    # Call wrapup_filter_bed_to_reduce
    # and store the returned GRanges in the list
    gr <- wrapup_filter_bed_to_reduce(file, prediction_dir)

    # Extract the base name of the file without the extension to use as the name
    file_name <- tools::file_path_sans_ext(basename(file))

    # Add the GRanges object to the GRangesList with the file name as the name
    gr_list[[file_name]] <- gr
  }

  # Return the combined GRangesList with names
  return(gr_list)
}


#' Run the PRIMEloci Workflow
#'
#' This function encapsulates the entire PRIMEloci workflow,
#' including creating profiles, running a Python script for profile prediction,
#' and processing the results into a `GRangesList`.
#'
#' @param ctss_rse A `SummarizedExperiment` object containing CTSS data.
#' @param tc_grl A `GRangesList` object containing TC data.
#' @param config_file Character. Path to the configuration file in YAML format.
#' Default is "config_R_PRIMEloci.yaml".
#'
#' @return A `GRangesList` containing the processed results.
#'
#' @details
#' This function orchestrates the PRIMEloci workflow, including:
#' - Setting up necessary directories based on the configuration file.
#' - Creating profiles using the CTSS and TC data.
#' - Running a Python script for predicting profile probabilities.
#' - Processing the output files and returning a `GRangesList` object.
#'
#' The workflow relies on configuration parameters specified in a YAML file.
#'
#' @importFrom yaml read_yaml
#' @importFrom tools file_path_sans_ext
#' @importFrom assertthat assert_that
#' @importFrom data.table fread fwrite
#' @importFrom argparse ArgumentParser
#' @importFrom foreach foreach %dopar%
#' @importFrom doParallel registerDoParallel stopImplicitCluster
#' @importFrom parallel detectCores
#' @importFrom GenomicRanges GRangesList sort
#' @importFrom rtracklayer import
#' @importFrom reticulate py_run_string
#'
#' @examples
#' \dontrun{
#' ctss_rse <- loadRDS("path_to_ctss_rse.rds")
#' tc_grl <- loadRDS("path_to_tc_grl.rds")
#' gr_list <- run_PRIMEloci(
#'   ctss_rse = ctss_rse,
#'   tc_grl = tc_grl,
#'   config_file = "config_PRIMEloci.yaml"
#' )
#' }
#' @export
run_PRIMEloci <- function(ctss_rse,
                          tc_grl,
                          config_file = "config_R_PRIMEloci.yaml") {

  # Load configuration from YAML file
  config <- yaml::read_yaml(config_file)

  # Set up directories and file paths based on config
  prediction_dir <- file.path(config$output_dir,
                              config$profile_main_dir,
                              "predictions",
                              config$profile_sub_dir)
  outdir_main_name <- c("metadata",
                        "profiles",
                        "profiles_subtnorm",
                        "predictions")
  outdir_subdir_name <- config$profile_sub_dir

  # Create output directories
  prep_profile_dir(output_dir = config$output_dir,
                   output_dir_name = config$profile_main_dir,
                   output_main_name = outdir_main_name,
                   output_subdir_name = outdir_subdir_name)

  # Create profiles for the specified subdir_name
  writeLines(paste0("\nCreating profiles for ", outdir_subdir_name, ".."))
  wrapup_make_profiles(ctss_rse,
                       tc_grl,
                       config$output_dir,
                       config$profile_main_dir,
                       outdir_subdir_name,
                       config$ext_dis,
                       save_count_profiles = config$save_count_profiles, # nolint: line_length_linter.
                       file_type = config$profile_file_type)

  writeLines("\n### Finished profile creation ###\n")

  # Run Python script for profile prediction


  run_prediction_python_script(
    script_path = "_predict_profile_probabilities.py",
    script_dir = config$python_script_dir,
    profile_main_dir = file.path(config$output_dir, config$profile_main_dir),
    profile_sub_dir = config$profile_sub_dir,
    model_path = config$model_path,
    name_prefix = config$prefix_out_name,
    threshold = config$threshold,
    file_format = config$profile_file_type
  )

  # Call the main function with the parsed argument
  gr_list <- process_all_files(prediction_dir, config$partial_name)

  writeLines("Done!")

  return(gr_list)
}