name: prime-env
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy>=2.0.2
  - scipy>=1.13
  - lightgbm>=4.6.0
  - pandas>=2.1
  - scikit-learn>=1.4
  - joblib>=1.2
  - pyarrow>=14
  - fastparquet>=2023.4
  - python>=3.9
  - libxml2
